### ISSUE TITLE
Channel was never opened

### ISSUE THREAD

**Issue by deepy420** [lnd-routing/lnd-routing#4]
I used the following keysend command and never received a channel opened in return. I also never received a refund for my payment.

lncli sendpayment --keysend  --amt 25500 \
 --dest 02ab583d430015f3b6b41730434b5fac264901b50199f0b9becc0a98a365f581a9 \
 --data 1667785070=01,34349339=03cd502dee15bb9859a6d9c56a5608c1f76894736ec4cfec906eb025b7623293dc

**Comment by deepy420** [comment]
Received the channel, thanks!

**Comment by lnd-routing** [comment]
Sorry about that, we have been experiencing what seems to be a DoS attack, and having to restart LND. At some point, our channel opening service didn't get restarted with it, it processed your payment as soon as it started up.
