### ISSUE TITLE
Default answer for private in script

### ISSUE THREAD

**Issue by ztankoz** [lnd-routing/lnd-routing#6]
https://github.com/lnd-routing/lnd-routing/blob/8b51cb4a71a909297052006d48bd25d99b0c3879/request_channel.py#L149
should be:

if pub_chan == 'Y' or pub_chan == '':
	request_code = '01'
else:
	request_code = '02'

or better

if pub_chan == 'N':
	request_code = '02'
else:
	request_code = '01'

otherwise, the script sets 02 when the default response is selected

**Comment by lnd-routing** [comment]
Fixed, thanks!
